name: "Yet Another AUR Publish"
description: "Dead simple AUR publisher"
author: loqusion
branding:
  color: blue
  icon: package
inputs:
  ssh-private-key:
    description: "The private SSH key to use to push the changes to AUR"
    required: true
  package-name:
    description: "AUR package name"
    default: ${{ github.event.repository.name }}
  git-username:
    description: "The username to use when creating the AUR repo commit"
    default: "AUR Release Action"
  git-email:
    description: "The email to use when creating the AUR repo commit"
    default: "github-action-bot@no-reply.com"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_SSH_PRIVATE_KEY: ${{ inputs.ssh-private-key }}
    INPUT_PACKAGE_NAME: ${{ inputs.package-name }}
    INPUT_GIT_USERNAME: ${{ inputs.git-username }}
    INPUT_GIT_EMAIL: ${{ inputs.git-email }}
