name: "Yet Another AUR Publish"
description: "Publish an AUR package"
author: loqusion
branding:
  color: blue
  icon: package
inputs:
  ssh-private-key:
    description: "The private SSH key to use to push the changes to AUR"
    required: true
  package-name:
    description: "AUR package name"
    default: ${{ github.event.repository.name }}
  git-username:
    description: "The username to use when creating the AUR repo commit"
    default: "AUR Release Action"
  git-email:
    description: "The email to use when creating the AUR repo commit"
    default: "github-action-bot@no-reply.com"
  debug:
    description: "If true, doesn't actually publish"
    default: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.package-name }}
    - ${{ inputs.git-username }}
    - ${{ inputs.git-email }}
    - ${{ inputs.ssh-private-key }}
